version: '{build}'
environment:
  CLI_VERSION: latest
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
skip_tags: true
build_script:
  - ps: .\build.ps1 -VersionAndPublish (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER)
test: off
artifacts:
- path: .\**\*.nupkg
  name: NuGet
nuget:
  disable_publish_on_pr: true 
deploy:  
- provider: NuGet
  api_key:
    secure: CxMH3k6k/Rpz1zjToGDAelLWDT/gDqRo08iEUAQsRnL+WRo+4TL5gLiNEUy/GfUy
  on:
    branch: 
    - master
    - /release\/[0-9]\.[0-9]/
